version: '3.8'

networks:
    app_network:
        driver: bridge

services:
    nginx:
        build:
            context: .
            dockerfile: _docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/backend
            - ./_docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./_docker/nginx/log:/var/log/nginx
        ports:
            - ${PORT}:80
        depends_on:
            - backend
        container_name: project_nginx
        networks:
            - app_network

    backend:
        container_name: project_app
        tty: true
        build:
            context: .
            dockerfile: _docker/backend/Dockerfile
        volumes:
            - ./:/var/www/backend
        depends_on:
            - app_db
#            - node
        ports:
            - 3000:3000
        networks:
            - app_network

    app_db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: app_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: app_db
        networks:
            - app_network

#    node:
#        image: node:16
#        tty: true
#        entrypoint: [ "npm" ]
#        restart: always
#        working_dir: /var/www/backend
#        volumes:
#            - "./www/:/var/www/my_shiny_project"
#        networks:
#            - app_network
#    node:
#        container_name: project_node
#        tty: true
#        image: node:16-alpine
#        restart: on-failure
#        hostname: node
#        working_dir: /var/www/backend
#        command: [ ]
#        depends_on: [ ]
#        networks:
#            - app_network
