version: '3.8'

networks:
    app_network:
      driver: bridge

services:
    nginx:
        container_name: "nginx_${APP_NAME}"
        build:
            context: .
            dockerfile: _docker/prod/nginx/Dockerfile
        volumes:
            - ./:/var/www/app
            - ./_docker/prod/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./_docker/prod/nginx/log:/var/log/nginx
        ports:
            - ${PORT}:80
        depends_on:
            - app
        networks:
            - app_network

    app:
        container_name: "backend_${APP_NAME}"
        tty: true
        build:
            context: .
            dockerfile: _docker/dev/backend/Dockerfile
        volumes:
            - ./:/var/www/app
        depends_on:
            - app_db
#            - node
        ports:
            - 3000:3000
        networks:
            - app_network

    app_db:
        container_name: "db_${APP_NAME}"
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - app_network
