/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors')
module.exports = {
    darkMode: 'media',
    content: [
        './index.html',
        './src/**/*.{vue,js,ts,jsx,tsx}',
        './storage/framework/views/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    theme: {
        screens: {
            'xs': '375px',
            'sm': '540px',
            'md': '720px',
            'lg': '960px',
            'xl': '1140px',
            '2xl': '1550px',
        },
        container: {
            center: true,
            padding: '20px',
        },
        fontFamily: {
            'sans': ['Gilroy', 'sans-serif'],
        },
        fontSize: {
            'xxs': ['14px', '1.6em'],
            'xs': ['16px', '1.6em'],
            'sm': ['18px', '1.6em'],
            'md': ['20px', '1.45em'],
            'lg': ['26px', '1.3em'],
            'xl': ['36px', '1.3em'],
            '2xl': ['64px', '1.1em'],
            '3xl': ['96px', '1.1em'],
        },
        extend: {
            colors: {
                white: "#FFF",
                purple: "#7843E9",
                pink: "#EC4176",
                dark: "#222",
                gray: "#454545",
                darkblue: "#1E1F43",
                body: '#BDBECA',
                card: '#323359',
                inherit: 'inherit',
                'dodger-blue': '#49B9FF',
                'onahau': '#CCEBFF',
                'gray-sec': '#F3F4F7',
                'd-gray-sec': '#15181E',
                'gray-high': '#F1F6F9',
                'd-gray-high': '#222630',
                'red': '#DD4333',
                'd-red': '#DD3929',
                'yellow': '#FFDC49',
                'green': '#15A250',
                'd-green': '#159846',
                'gray-santas': '#959DAE',
                'gray-river': '#444B59',
                'alto': '#D3D3D3',
                'mercury': '#E5E5E5',
                'alabaster': '#FAFAFA',
                'gallery': '#F0F0F0',
                'gray-dusty': '#999999',
                'gray-dove': '#666666',
                'silver': '#C4C4C4',
                'silverdark': '#AAAAAA',
                'wildsand': '#F4F4F4',
                'mineshaft': '#333333',
                'red-tw': colors.red,
                'yellow-tw': colors.amber,
                'green-tw': colors.emerald,
                'beige': '#F4F1D9',
                'spring-wood': '#f2f4e8',
            },
        },
    },
    plugins: [
        require('@tailwindcss/line-clamp'),
    ],
}
